### ISSUE TITLE
Don't panic on all GetEntries errors

### ISSUE THREAD

**Issue by Laur1nMartins** [nore-dev/fman#14]
When you go to a folder the app can't access or the file path gets malformed in some way the app just crashes. Looking at the code it seems that this behaviour stems from the `Update` function on the `ListModel`. I suggest doing some form of error validation to check if the error is recoverable or indeed a panic must happen.

Due to the fact that this implies some design decisions as to how to handle this from a UI perspective I don't think that doing a pull request with my own solution will be beneficial. If there is anything I can help with let me know.

**Comment by Laur1nMartins** [comment]
An example: opening `fman` in any folder and then spamming the left arrow key panics with:
`stat usr/bin: no such file or directory`

**Comment by nore-dev** [comment]
thank you!

**Comment by nore-dev** [comment]
@Laur1nMartins it does not panic now but still gives an error. Can you help? 
`read /: is directory`

**Comment by nore-dev** [comment]
using os.Chdir() seems to fix the problem
