### ISSUE TITLE
vim movements - 'j' and 'k' - is the mapping correct?

### ISSUE THREAD

**Issue by dzzzchhh** [nore-dev/fman#18]
Hi! Forgive me for being picky, but I was at first disoriented by how `j` and `k` keys are mapped by default.

https://github.com/nore-dev/fman/blob/fd1d4e7417bcc4e59170d23cbf56d649ad7c8a04/model/list.go#L250
https://github.com/nore-dev/fman/blob/fd1d4e7417bcc4e59170d23cbf56d649ad7c8a04/model/list.go#L257

The reason for my confusion is the fact that I'm used to `j` being responsible for moving the cursor down instead of up, as portrayed [here](https://vim.rtorr.com), for example.

Was just wondering if this is intended 🤔 

Thanks in advance!

**Comment by nore-dev** [comment]
my bad
